language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script:
  - flake8 api --exclude api/migrations,api/tests
  - python manage.py test api.tests --noinput
  - coverage run manage.py test api.tests --noinput
after_success:
  - coveralls