# Generated by Django 2.0.3 on 2018-04-26 16:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180426_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeresult',
            name='detail',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='judgespec',
            name='config',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
    ]
