# Generated by Django 2.0.3 on 2018-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180509_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymproblem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
