# Generated by Django 2.0.3 on 2018-05-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180513_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name': '도장', 'verbose_name_plural': '도장'},
        ),
        migrations.AlterModelOptions(
            name='judgeresult',
            options={'verbose_name': '채점결과', 'verbose_name_plural': '채점결과'},
        ),
        migrations.AlterModelOptions(
            name='judgespec',
            options={'verbose_name': '채점기준', 'verbose_name_plural': '채점기준'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': '문제', 'verbose_name_plural': '문제'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': '제출', 'verbose_name_plural': '제출'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
    ]
