# Generated by Django 2.0.3 on 2018-05-30 10:43

import api.s3
import coding.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180523_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_data',
            field=models.FileField(storage=coding.custom_storages.MediaStorage(), upload_to=api.s3.get_submission_path),
        ),
    ]
