# Generated by Django 2.0.5 on 2018-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180523_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='lang_profile',
            new_name='lang'
        ),
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('c++', 'CPP'), ('java', 'JAVA'), ('python3', 'PYTHON3'), ('go', 'GO')], default='CPP', max_length=20),
        ),
        migrations.AlterField(
            model_name='judgeresult',
            name='status',
            field=models.CharField(choices=[('ENQ', 'ENQUEUED'), ('IP', 'IN_PROGRESS'), ('CTE', 'COMPILE_ERROR'), ('PASS', 'PASSED'), ('FAIL', 'FAILED'), ('ERR', 'INTERNAL_ERROR')], max_length=255),
        ),
    ]
