# Generated by Django 2.0.5 on 2018-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180525_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judgeresult',
            name='time_elapsed_seconds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('c++', 'CPP'), ('java', 'JAVA'), ('python3', 'PYTHON3'), ('go', 'GO')], max_length=20),
        ),
    ]
