# Generated by Django 2.0.3 on 2018-06-05 18:26

import api.s3
import coding.custom_storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180528_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Submission'),
        ),
        migrations.AlterField(
            model_name='judgespec',
            name='grader',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='judgespec',
            name='test_data',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='judgespec',
            name='time_limit_seconds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_data',
            field=models.FileField(storage=coding.custom_storages.MediaStorage(), upload_to=api.s3.get_submission_path),
        ),
    ]
